SELECT
       POD.EXT_UI,
       EUIINSTLN.ANLAGE,
       Customer.MRU,
       ISU_ADR2.TELNR_LONG,
       Customer.CONTRACT_ACCOUNT_NAME,
       Customer.ACCOUNT_TYPE,
       Customer.BUSINESS_PARTNER_NUMBER
FROM 
       COMMERCIAL.ISU_POD POD
       INNER JOIN
             CUSTOMER.EUITRANS EUITRANS
             ON EUITRANS.EXT_UI = POD.EXT_UI
             AND CURRENT_DATE BETWEEN EUITRANS.DATEFROM AND EUITRANS.DATETO
       INNER JOIN
             COMMERCIAL.EUIINSTLN EUIINSTLN
             ON EUIINSTLN.INT_UI = EUITRANS.INT_UI
             AND CURRENT_DATE BETWEEN EUIINSTLN.DATEFROM AND EUIINSTLN.DATETO
       INNER JOIN
              COMMERCIAL.HNODS_ST_BILL_CUSTOMER_MONTHLY_SNAPSHOT Customer
             ON Customer.Installation_Number = EUIINSTLN.ANLAGE
             AND Customer.Month_Start_Date = CURRENT_DATE


             LEFT OUTER JOIN
                    "COMMERCIAL"."ISU_BUT021_FS" ISU_BUT021_FS
                    ON ISU_BUT021_FS.PARTNER = Customer.BUSINESS_PARTNER_NUMBER
             LEFT OUTER JOIN
                    "CUSTOMER"."ISU_ADR2" ISU_ADR2
                    ON ISU_ADR2.ADDRNUMBER = ISU_BUT021_FS.ADDRNUMBER
       WHERE
             ISU_ADR2.TELNR_LONG LIKE ('+614%')
and POD.EXT_UI IN        
('55106573693',
'55104971859')
